name: Python Flake8 Linter
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flake8 linter
        run: pip install flake8
      - name: Setup Flake8 output matcher for PR annotations
        run: echo '::add-matcher::.github/workflows/flake8-pr-annotation-matcher.json'
      - name: Get names of changed files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: echo CHANGED_FILENAMES="$(gh pr view --repo reepoi/pvlib-python ${{ env.PR_NUMBER }} --json files -q '[.files[].path] | @csv')"
             >> ${{ github.env }}
      - name: Run Flake8 linter
        run: flake8
               ${{ env.CHANGED_FILENAMES }}
               --exclude pvlib/version.py
               --ignore E201,E241,E226,W503,W504
               --max-line-length 79
               .
